//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlParser_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreationInfo
    {
        public CreationInfo()
        {
            this.Person = new Person();
            this.Tool = new Tool();
        }
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string User_ID { get; set; }
        public Nullable<int> Tool_ID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
