//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlParser_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public MetaData()
        {
            this.CreationInfo = new CreationInfo();
        }
        public int Id { get; set; }
        public string Schemaversion { get; set; }
        public string SchemaType { get; set; }
        public Nullable<int> CreationInfo_ID { get; set; }
    
        public virtual CreationInfo CreationInfo { get; set; }
    }
}
