//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlParser_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string Id { get; set; }
        public string system43PersonId { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public Nullable<long> telephone { get; set; }
        public string email { get; set; }
    }
}
