//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlParser_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string version { get; set; }
    }
}
